package:
  name: pygridplot
  version: v0.0.1

source:
  git_url: https://github.com/Geosyntec/pygridplot.git
  git_tag: v0.0.1
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 0
  skip: True # [win]
  script: python setup.py install

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy
    - matplotlib
    - pyproj
    - pyshp
    - shapely
    - pygridtools

test:
  imports:
    - pygridplot

  commands:
    - python -c "import pygridplot; pygridplot.test()"

  requires:
    - nose

about:
  home: http://github.com/Geosyntec/pygridplot
  license:  BSD License
  summary: 'Visualizing model results on grids.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml/configure
