package:
  name: pygridplot
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v0.0.1') }}


source:
  path: ../../
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  skip: True # [win]
  script: python setup.py install

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy
    - matplotlib
    - pyproj
    - pyshp
    - shapely
    - pygridtools

test:
  imports:
    - pygridplot

  commands:
    - python -c "import pygridplot; pygridplot.test()"

  requires:
    - nose

about:
  home: http://github.com/Geosyntec/pygridplot
  license:  BSD License
  summary: 'Visualizing model results on grids.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml/configure
